# Generated by Django 4.1.6 on 2023-03-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_setup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setup',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='setup',
            old_name='setup_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='setup',
            old_name='setup_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='setup',
            old_name='setup_name',
            new_name='name',
        ),
    ]
