# Generated by Django 4.1.6 on 2023-03-07 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_alter_setup_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setup',
            options={'ordering': ['name'], 'verbose_name_plural': 'Setups'},
        ),
        migrations.AlterField(
            model_name='setup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setups', to=settings.AUTH_USER_MODEL),
        ),
    ]
