# Generated by Django 4.1.6 on 2023-02-27 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='BlogCategory',
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name_plural': 'Blog Categories'},
        ),
        migrations.RenameField(
            model_name='blogcomment',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
